### ISSUE TITLE
Initialization autoloaded the constants ActionText::ContentHelper using Rails 6.0.3.1

### ISSUE THREAD

**Issue by gbarillot** [metaskills/minitest-spec-rails#103]
Hi,

On a fresh new Rails app (6.0.3.1) with only minitest-spec-rails Gem installed I get this error:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
```

I also tried installing from straight from Github, but the result is the same. Is there anything I have to tweak in some initializer / config file first, or is it a bug in minitest-rails-spec?

Can provide a link to a demo app if needed.

**Comment by metaskills** [comment]
Hmm, I, and I think a few others, are using this gem with Rails v6 without issue. But I don't have ActionText setup with my app. Maybe it needs an on load here? https://github.com/metaskills/minitest-spec-rails/blob/master/lib/minitest-spec-rails/railtie.rb
