### ISSUE TITLE
Cheetsheet link dead

### ISSUE THREAD

**Issue by Merovex** [metaskills/minitest-spec-rails#107]
Howdy.

Looking at the Readme, there's a reference to a cheetsheet at (http://cheat.errtheblog.com/s/minitest). That link appears dead.

**Comment by metaskills** [comment]
Thanks! I updated it with this one: https://chriskottom.com/freebies/cheatsheets_free.pdf Open to a different or better one if you have a recommendation too.

**Comment by Merovex** [comment]
No suggestions. I'm coming back to Rails after...too many years in PM; and automated testing is greenfield for me.
