### ISSUE TITLE
minitest-spec-rails/parallelize.rb:18 - Stack Level Too Deep

### ISSUE THREAD

**Issue by jarblz** [metaskills/minitest-spec-rails#127]
Hi there! I'm coming across an issue with either this gem, or maybe its relationship to my rails version, or possibly the `minitest-rails` gem.  I recently upgraded to `rails 7.0.8.5` from `7.0.3.1`.  which caused me to need to update this gem (which was previously at 6.0.1), to pick up [version 7.1.1 of this gem, to resolve the `MiniTest`/ `Minitest` discrepancy](https://github.com/metaskills/minitest-spec-rails/commit/c7e84c7d96e27cf48e1ca6d9ecaa9210d78c1a90).

I'm now seeing this error when trying to run my minitest specs: 
```
/usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe': stack level too deep (SystemStackError)
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/parallelize.rb:18:in `describe'
	 ... 7268 levels...
	from /usr/local/bundle/gems/minitest-rails-7.0.1/lib/minitest/rails/parallelize.rb:29:in `describe'
	from /usr/local/bundle/gems/minitest-spec-rails-7.4.1/lib/minitest-spec-rails/dsl.rb:12:in `describe'
	from test/serializers/v2_segment_serializer_test.rb:7:in `<class:V2SegmentSerializerTest>'
	from test/serializers/v2_segment_serializer_test.rb:3:in `<main>'
```
[here is my gemfile.lock](https://github.com/user-attachments/files/17834932/Gemfile.lock.txt)
and my [gemfile](https://github.com/user-attachments/files/17834933/Gemfile.txt)

**Comment by metaskills** [comment]
I would be curious if locking this gem to v7.3.0 helps?

**Comment by jarblz** [comment]
> I would be curious if locking this gem to v7.3.0 helps?

Thanks for the quick reply! that yields the same result unfortunately.  Does this gem have any version requirement for the `minitest-rails` gem? i see that in the trace..

**Comment by metaskills** [comment]
No. I would have assumed using minitest-rails is an either/or. Not both. At least last I checked. Does that help?

**Comment by jarblz** [comment]
yes! super helpful, thanks for being a good samaritan and helping out a total stranger lol.  I work on a big monolith and it turns out your exactly right, they had both gems in there erroneously.  Not sure why it didn't blow up until now, but it looks like both gems had methods overriding the minitest describe block and that was causing weirdness.  I removed `minitest-rails` and it resolved the issue.  YOU ROCK 🎸
