### ISSUE TITLE
How to write routing tests?

### ISSUE THREAD

**Issue by jasperkennis** [metaskills/minitest-spec-rails#22]
I'm having some trouble running routing tests and I'm not sure if I'm doing it wrong or it's a problem with the `minitest-spec-rails` gem. This is my test:

``` ruby
require "test_helper"

class HomepageRouteTest < ActionDispatch::IntegrationTest
  def test_homepage
    assert_routing "/", :controller => "home", :action => "index"
  end
end
```

but the error I'm getting is:

```
  1) Error:
HomepageRouteTest#test_homepage:
NoMethodError: undefined method `recognize_path' for nil:NilClass
    /Users/jasperkennis/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/testing/assertions/routing.rb:210:in `recognized_request_for'
    /Users/jasperkennis/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/testing/assertions/routing.rb:42:in `assert_recognizes'
    /Users/jasperkennis/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/testing/assertions/routing.rb:118:in `assert_routing'
    test/routes/homepage_test.rb:5:in `test_homepage'
```

and to be complete, this is my test helper file:

``` ruby
ENV["RAILS_ENV"] = "test"
require File.expand_path('../../config/environment', __FILE__)
```

**Comment by maxbeizer** [comment]
I know it's super late to the party, but I came across this thread trying to resolve `undefined method assert_routing`. I wanted to point out for anyone trying to solve that problem who ended up here that you can put the test in any subset of dirs and use the MiniTest DSL.

*major caveat*: you must have either "Acceptance Test" or "Integration Test" at the end of the describe block string. Convention over configuration, ftw.

Example:
```ruby
# /test/routing/some_test.rb
require 'test_helper'

describe "My Routing Integration Test" do
  describe "/some-route" do
    it "returns some_controller#some_action" do
      assert_routing '/some-route', controller: 'some_controller', action: 'some_action'
    end
  end
end
```
I'm using minitest-rails (2.1.1)

**Comment by metaskills** [comment]
Thanks, but this gem and mintest-rails are different entities and take drastically different approaches to how we integrate MT and Rails.

**Comment by maxbeizer** [comment]
@metaskills My apologies for the misplaced comment. I will delete, if you would like.

**Comment by metaskills** [comment]
No apology needed. There is no bad blood between the projects. Just wanted to point out the difference in case anyone treaded here. FYI, I could have deleted too, but that's not my style. Rock on!

**Comment by maxbeizer** [comment]
That's why I offered :wink: . Big hugs to all open source maintainers. Thank you for your continued contribution to us all.
