### ISSUE TITLE
Cannot use with database_cleaner gem

### ISSUE THREAD

**Issue by leebrooks0** [metaskills/minitest-spec-rails#44]
I am trying to use your gem with `database_cleaner`. In my `testhelper.rb` I have the following:

``` rb
require 'database_cleaner'
DatabaseCleaner.strategy = :truncation
MiniTest::TestCase.add_setup_hook { DatabaseCleaner.start }
MiniTest::TestCase.add_teardown_hook { DatabaseCleaner.clean }
```

The hooks are necessary as if you use before and after like they do here:
https://github.com/bmabey/database_cleaner
you will override them when you use `before` and `after` blocks in your test.

I keep getting this message though: 

``` sh
rake aborted!
NameError: uninitialized constant Minitest::TestCase
/home/lee/Code/mobifit/test/test_helper.rb:47:in `<top (required)>'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/sub_test_task.rb:113:in `each'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/sub_test_task.rb:31:in `create_and_run_single_test'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/sub_test_task.rb:17:in `invoke_rake_task'
/home/lee/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
-e:1:in `<main>'
Tasks: TOP => test:single
(See full trace by running task with --trace)

Googling yields nothing, so I don't know where the problem lies.
```

**Comment by dmvt** [comment]
`before` and `after` have been replaced with `setup` and `teardown` for anyone who is experiencing the `NoMethodError: undefined method `before' for ActiveSupport::TestCase:Class` error.

The following works in Rails 5:

```ruby
class ActiveSupport::TestCase
  include FactoryGirl::Syntax::Methods

  ActiveRecord::Migration.check_pending!
  DatabaseCleaner.strategy = :truncation
  DatabaseCleaner.logger = Rails.logger
  setup { DatabaseCleaner.start }
  teardown { DatabaseCleaner.clean }
end
```

**Comment by metaskills** [comment]
@dmvt The `setup` and `teardown` blocks have been in Rails for as long as I can remember. Rails has always made those methods use the callback chain so you can stack them up. This gem has always delegated to those methods so MiniTest's before/after syntax follows that practice. More details here:

* https://github.com/metaskills/minitest-spec-rails#setup--teardown-compatability
* https://github.com/metaskills/minitest-spec-rails/blob/master/lib/minitest-spec-rails/dsl.rb#L16-L22

Lastly, I have never had an issue using this gem with DatabaseCleaner. Hope that info is helpful if anyone is having issues. Please share details if you are.
