### ISSUE TITLE
Expected to work with Rails engines?

### ISSUE THREAD

**Issue by jrochkind** [metaskills/minitest-spec-rails#53]
It may be this is simply not expected to work with Rails engines?

I have a Rails engine skeleton created with `rails plugin new --full`.  This also creates a `dummy` Rails app for use under testing. The engine was created with and uses Rails 4.1. I include `minitest-spec-rails` in the Gemfile (and/or gemspec). (Is there any other setup other than this?)

But `undefined method`describe' for main:Object (NoMethodError)`

Am I doing something wrong, or is minitest-spec-rails  just not meant for Rails engines?

**Comment by kaorukobo** [comment]
I run into the same issue on `rails plugin new` skeleton. (Rails 5.2.1)

It worked fine by just appending `require 'minitest-spec-rails'` to `test/test_helper.rb` .
