### ISSUE TITLE
ActiveJob::TestCase support?

### ISSUE THREAD

**Issue by xpepermint** [metaskills/minitest-spec-rails#59]

**Comment by metaskills** [comment]
Oh, interesting. So this should work already since it all test cases subclass from `ActiveSupport::TestCase`?

**Comment by xpepermint** [comment]
Well... that's what I thought. I tried but it didn't work.

**Comment by metaskills** [comment]
Can you show me the test folder and file that Rails generates?

**Comment by metaskills** [comment]
For an ActiveJob test please.

**Comment by xpepermint** [comment]
Here you go: http://guides.rubyonrails.org/testing.html#testing-jobs

**Comment by metaskills** [comment]
Well, it does sub class as I suspected, you [can see here](https://github.com/rails/rails/blob/master/activejob/lib/active_job/test_case.rb). That means this should work correct?

```ruby
class BillingJobTest < ActiveJob::TestCase
  let(:account) { ... }
  it 'some spec' do
    
  end
end
```

Or are you trying to use the [non recommended outer describe](https://github.com/metaskills/minitest-spec-rails#test-styles) syntax? If so, I can add support for that soon.

**Comment by xpepermint** [comment]
ow... I see... I was using the describe... that should do the trick... support would be great anyway... thanks!

**Comment by metaskills** [comment]
Cool, I'll get to that soon. FYI, I always recommend doing explicit subclassing. Staying close to Rails' existing structure will pay dividends on avoid crazy auto/magic subclassing issues I have seen happen. Cheers and thanks for the heads up.

**Comment by xpepermint** [comment]
Yeah... I move my tests from rspec and cucumber and I try to get the same `aestetic` :). Thanks man!

**Comment by metaskills** [comment]
Done deal, just released v5.2.0. Please let me know if there are any issues.

**Comment by xpepermint** [comment]
thx!

**Comment by jaredbeck** [comment]
> Yeah... I move my tests from rspec and cucumber and I try to get the same [aesthetic]

Me too.  Ken and I had an interesting talk about subclassing vs. outer-describe in issue #56  check out e.g. this part: https://github.com/metaskills/minitest-spec-rails/issues/56#issuecomment-67179866

> Rspec 3 is also moving away from this "test-type inference", as described in this line from the rspec 3.0 release notes.
>
>> Spec types are no longer inferred by location, they instead need to be explicitly tagged. The old behaviour is enabled by config.infer_spec_type_from_file_location!, which is still supplied in the default generated spec_helper.rb. (Xavier Shay, Myron Marston)
https://www.relishapp.com/rspec/rspec-rails/v/3-1/docs/changelog
>>

This led to the recommendation in the readme but maybe this is still a pain point (a "gotcha") for people who were used to using outer-describe in rspec 2.  

Maybe we should discuss deprecating outer-describe?

**Comment by metaskills** [comment]
> Maybe we should discuss deprecating outer-describe?

Indeed, I got a little more honest about this in the README just now too. Thanks!

https://github.com/metaskills/minitest-spec-rails#test-styles
