### ISSUE TITLE
described_class references the TestCase class in some scenarios

### ISSUE THREAD

**Issue by zacstewart** [metaskills/minitest-spec-rails#67]
When a describe block is labeled with a `::` prefix to denote class methods, `described_class` resolves the wrong constant. Instead of the subject class, it gets the test class itself.

```ruby
require 'minitest/autorun'
require 'test_helper'
require 'json_web_token'

class JsonWebTokenTest < ActiveSupport::TestCase
  describe '::encode' do
    let(:claims) { {'user_id' => 555} }

    it 'encodes a hash of claims to a URL safe string' do
      described_class.encode(claims)
      # => NoMethodError: undefined method `encode' for JsonWebTokenTest:Class
    end
  end
end
```

Changing `describe '::encode'` to `describe '.encode' fixes it.

**Comment by metaskills** [comment]
Very Interesting. Can you think of a change to this (https://github.com/metaskills/minitest-spec-rails/blob/master/lib/minitest-spec-rails/init/active_support.rb#L12-L21) that would help with that scenario? Nothing is coming to mind for me now.

**Comment by metaskills** [comment]
Ah... it would be a limitation of ActiveSupport's [determine_constant_from_test_name](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/testing/constant_lookup.rb) method. I guess you just have to use `describe ".encode" do` instead which I confirmed works just fine. Cool?

**Comment by zacstewart** [comment]
Yeah, it's not a huge turnoff. I just like the say '::method_name' echos documentation. You can close this for now, but I might try to send a PR eventually.

**Comment by zacstewart** [comment]
Thanks for taking a look at it though!

**Comment by metaskills** [comment]
Cool, thanks Zac. I searched rails/rails and found no previous bug reports on that method too. Cheers!
