### ISSUE TITLE
more information

### ISSUE THREAD

**Issue by BKSpurgeon** [metaskills/minitest-spec-rails#83]
Hi folks

Ken directed me to this website after I started using Rspec for rails. that's a no-no so i took his advice. now i need to get all of the rspec stuff out and all the minitest stuff in. better now than later i figure.

I am looking for bare-bones basics on how to set up a test.

would the minitest-spec tutorials suffice? e.g. how to set up a 'hello-world' test.

i need to know basics like: where the tests should be placed? how the tests should be run? etc.

any advice much appreciated.

rgds

Ben

**Comment by metaskills** [comment]
Hey! Ken here :) Sorry for the late reply.

>  minitest-spec tutorials suffice

No... they are a bolt on to Rails and differ from core. To get started with testing is as simple as reading Rails testing guides. 

http://guides.rubyonrails.org/testing.html

The only thing this gem does is allow you to use the Minitest Spec DSL within the same ActiveRecord test setup. For example, lets say you generated a model test called UsersTest, it would look like this:

```ruby
require 'test_helper'
class UserTest < ActiveSupport::TestCase
  test "email" do
    assert_equal 'test@example.com', user.email
  end
end
```

This gem allows you to change that `test` to a spec style syntax to something like this.

```
  it "email" do
    user.email.must_equal 'test@example.com', 
  end
```

Which also opens up the whole other aspects of the Spec syntax, let, describe, etc. Hope that helps.

**Comment by BKSpurgeon** [comment]
I see. So the best advice is to read the rails testing guide (which I wasn't aware of btw - thanks for that) and to then use minitest to test rails. I shouldn't use minitest-spec because they are a bolt-on to rails (i.e. they reproduce rails functionality).

I"ll go through the testing guidelines quite closely. thanks for that.

**Comment by metaskills** [comment]
I made a few changes to the README that will hopefully lighten up the noise of the docs before learning more on what this project is and how to go about using it. Thanks so much of opening the issue and starting the conversation. Happy testing and cheers!

**Comment by BKSpurgeon** [comment]
thank you sir i look fwd to going through it all. i will post my comments if doubts arise. chrs
